

name: Build Test and Deploy

on:
  push:
    # branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-and-test:
    needs: test-security
    runs-on: ubuntu-latest

    # strategy:
    #   matrix:
    #     node-version: [16.x, 18.x, 20.x]
    #     # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - name: Checout the repository 
      uses: actions/checkout@v3
    - name: Use Node.js 18
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
        cache: 'npm'
    - name: Install dependences 
      run: npm install
    - name: Run intefration tests
      run: npm test

  test-security:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x, 20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - name: Checout the repository 
      uses: actions/checkout@v3
    - name: Use Node.js ${{matrix.node-version}}
      uses: actions/setup-node@v3
      with:
        node-version: ${{matrix.node-version}}
        cache: 'npm'
    - name: Install dependences 
      run: npm install
    - name: Run intefration tests
      run: npm run test-npm-security

  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to production
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.SERVICE_ID }}
          api-key: ${{ secrets.RENDER_TOKEN }}
          wait-for-success: true